# 简化版本
name: Build and Release server.jar

on:
  push:
    tags: ['v*']  # 只在打标签时运行
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Build Paper server
      run: |
        chmod +x gradlew
        ./gradlew clean
        ./gradlew applyPatches
        ./gradlew createMojmapPaperclipJar

    - name: Find and rename JAR
      run: |
        # 查找并重命名为 server.jar
        JAR_FILE=$(find . -name "paperclip-mojmap-*.jar" | head -n 1)
        [ -z "$JAR_FILE" ] && JAR_FILE=$(find . -name "paper-*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -n 1)
        cp "$JAR_FILE" server.jar
        echo "File size: $(ls -lh server.jar | awk '{print $5}')"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: server.jar
        tag_name: ${{ github.ref_name }}
        name: "Server ${{ github.ref_name }}"
        body: "Server JAR build from ${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
