name: Build and Release Paper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build Paper server
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew applyPatches
          ./gradlew createMojmapPaperclipJar

      - name: Find and rename JAR
        run: |
          # 查找并重命名为 server.jar
          JAR_FILE=$(find . -name "paperclip-mojmap-*.jar" | head -n 1)
          [ -z "$JAR_FILE" ] && JAR_FILE=$(find . -name "paper-*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -n 1)
          cp "$JAR_FILE" server.jar
          echo "文件大小: $(ls -lh server.jar | awk '{print $5}')"

      - name: Create or Overwrite Release
        uses: actions/create-release@v1
        with:
          tag_name: "latest"
          release_name: "Paper Server - Latest"
          body: |
            最后更新: $(date)
            提交: ${{ github.sha }}
            文件大小: $(ls -lh server.jar | awk '{print $5}')
          draft: false
          prerelease: false
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./server.jar
          asset_name: server.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
